### ISSUE TITLE
staff

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#23]
<img width="1280" alt="screen shot 2015-07-26 at 7 40 13 am" src="https://cloud.githubusercontent.com/assets/13425917/8893934/9208feb0-3369-11e5-8ece-6c4a911b5bc4.png">

tampoco lo de staff y i need to see it pa compararlo con una lista updateada de los miembros por si nos falto escribir a alguien please

**Comment by danielwatson6** [comment]
duplicate of #22. already fixing
