### ISSUE TITLE
Lower sidebar logo resolution

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#25]
el logo del side bar creo que demora mucho en cargarse ahora que probamos que las fotos se pueden subir en 1024 pixeles ... quieres que te lo mande again en una resolucion mas baja para que se cargue más rapido?

**Comment by danielwatson6** [comment]
@christineortiz7 dale, el width que el sidebar usa en el website es solo 360px, es cierto que es un gasto de performance usar el de ahora (>3000px width). uno de 1024 o 512 de ancho debe ser suficiente

**Comment by christineortiz7** [comment]
dale ahorita te mando el link por fb
