### ISSUE TITLE
carrusel

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#26]
<img width="1280" alt="screen shot 2015-07-26 at 7 44 09 am" src="https://cloud.githubusercontent.com/assets/13425917/8893950/2260cdda-336a-11e5-8b32-c7e633dd4454.png">

en el carrusel ya no me sale el nombre del tab y el nombre del articulo ni la barra esa de color que antes salia

**Comment by danielwatson6** [comment]
el carousel no funciona bien en el live app, pero en localhost no tiene problemas. voy a dejar esto en #18
