### ISSUE TITLE
Add spacing and crop pictures in gallery

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#42]
<img width="1280" alt="screen shot 2015-07-27 at 12 14 46 am" src="https://cloud.githubusercontent.com/assets/13425917/8899020/8f4680b8-33f4-11e5-846b-2df8de60de52.png">

falta espacio entre las fotos y hay que hacerle un fix pa poder subir fotos verticales y que no se vean asi como en el screenshot, te mande mi posible solucion por whatsapp pero probablemente no se de que estoy hablando jajajaja

**Comment by danielwatson6** [comment]
fixed by #50
