### ISSUE TITLE
staff

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#43]
<img width="1280" alt="screen shot 2015-07-27 at 12 16 38 am" src="https://cloud.githubusercontent.com/assets/13425917/8899029/cb4fdc76-33f4-11e5-94cc-59ffe3cfe352.png">

faltan bios y fotos en lq y hq de algunos (ahora mas tarde en la mañana te mando las HQ de los que te mande en low resolution hoy 
<img width="1280" alt="screen shot 2015-07-27 at 12 16 32 am" src="https://cloud.githubusercontent.com/assets/13425917/8899046/f844e262-33f4-11e5-9539-2347f958c1fc.png">

**Comment by danielwatson6** [comment]
duplicate of #40
