### ISSUE TITLE
Safari: sidebar remains fixed when scrolling back to top

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#5]
<img width="1280" alt="screen shot 2015-07-22 at 9 46 55 pm" src="https://cloud.githubusercontent.com/assets/13425917/8842090/63eb188e-30bb-11e5-9ed4-c4679f1abc4e.png">

**Comment by danielwatson6** [comment]
@christineortiz7 Solo puedo replicar el error en safari, y es como un delay cuando subes devuelta. Voy a ver como lo arreglo

**Comment by danielwatson6** [comment]
@christineortiz7 trata de replicar el error devuelta, ya a mi no me sale y eso que no le he metido especificamente a este bug

**Comment by danielwatson6** [comment]
fixed by #51
