### ISSUE TITLE
Justify and indent article content

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#6]
<img width="1280" alt="screen shot 2015-07-22 at 9 50 54 pm" src="https://cloud.githubusercontent.com/assets/13425917/8842139/01c61ca2-30bc-11e5-8fa3-acd4e9159a51.png">

Se puede poner indent y justificar el texto? y que cuando se baje al articulo que el sidebar siga viendose fixed to top?

**Comment by danielwatson6** [comment]
@christineortiz7 Voy a separar esto en dos issues.
