### ISSUE TITLE
Add UI message on newly added photos at home

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#67]
que sea temporal por mientras y escrito manual como si fuera un tab de live update pero que no diga '+leer mas' al final del mensaje

**Comment by danielwatson6** [comment]
@christineortiz7 yo sugeriria que el display sea como el del feature final. Le ponemos algo arriba en la pagina con una x para cerrarlo. Como esto pero que ocupe todo el width de la pagina, posiblemente con otro styling:

![screen shot 2015-08-29 at 5 11 31 pm](https://cloud.githubusercontent.com/assets/3270063/9564563/1370f29c-4e71-11e5-8369-22a59d7432d5.png)
