### ISSUE TITLE
Carousel images distorting

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#7]
<img width="1280" alt="screen shot 2015-07-22 at 9 54 36 pm" src="https://cloud.githubusercontent.com/assets/13425917/8842161/48b24d52-30bc-11e5-8d54-38df2938ef5b.png">

el ancho de las fotos del carrusel creo que es a bit much y esta deformando la pic

**Comment by danielwatson6** [comment]
@christineortiz7 Si queremos que las fotos queden del tamaño exacto del window, tienen que decidirse en un standard size para cada foto. Hay varias formas para resolver el problema pero depende de como sigamos: podemos hacer que la pagina recorte las fotos por su cuenta, no hacer lo de que quede el tamaño exacto, etc.

**Comment by christineortiz7** [comment]
que la pagina haga el recorte de la foto por su cuenta
