### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by danielwatson6** [djwatt5/the-cep-times#75]
@christineortiz7 let users search for albums, articles, categories?

**Comment by christineortiz7** [comment]
sip acuerdate que tambien habiamos hablado de tener tags en los posts para que si por ejemplo un articulo de deportes tiene los tags "copa talento, liga, futbol, femenina, equipo" puedan encontrar los articulos con esos tags

**Comment by christineortiz7** [comment]
tags/keywords
