### ISSUE TITLE
Sidebar musical note icon not centered

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#8]
<img width="362" alt="screen shot 2015-07-22 at 10 33 12 pm" src="https://cloud.githubusercontent.com/assets/13425917/8842605/cfa24452-30c1-11e5-9db1-157494224176.png">

el icon de musiquita no esta centreado

y creo que todavia nos falta el favicon?

**Comment by danielwatson6** [comment]
@christineortiz7 Si le dibujas un cuadrado alrededor enverdad sí está centrado. Igual lo moví un pixel arriba y un pixel abajo para que veas la diferencia.

1 Pixel arriba:

![screen shot 2015-07-23 at 8 07 17 am](https://cloud.githubusercontent.com/assets/3270063/8851004/2614350c-3112-11e5-9714-9d1be1fc62c5.png)

1 Pixel abajo:

![screen shot 2015-07-23 at 8 07 06 am](https://cloud.githubusercontent.com/assets/3270063/8851012/2ed2857c-3112-11e5-931d-a0207da9b7bd.png)

Podemos usarlo como está o el de arriba si te parece que se ve mejor.

**Comment by christineortiz7** [comment]
creo que prefiero el de arriba :)
