### ISSUE TITLE
Carousel images not appearing from newest to oldest

### ISSUE THREAD

**Issue by christineortiz7** [djwatt5/the-cep-times#9]
en el de meteor.com ya he subido como 6 articulos de mentira pero en el carrusel solo me salen las fotos de los primeros 3 que subi

**Comment by danielwatson6** [comment]
@christineortiz7 Habíamos puesto que el carousel tuviera máximo 3 fotos. Igual podemos cambiar el número a cuanto quieran. También deberían salir las más nuevas, eso si lo voy a arreglar.
